// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk-NcWt35jUOkp5MbWpT0RhuvegMtr5gI',
    appId: '1:112575088036:android:a0f3c6e0d7c81ced346d31',
    messagingSenderId: '112575088036',
    projectId: 'snack-n-snap',
    storageBucket: 'snack-n-snap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk7Gkrd-aMyARTajK3765pSQHSmbXp32E',
    appId: '1:112575088036:ios:a0f1aa3ab846388a346d31',
    messagingSenderId: '112575088036',
    projectId: 'snack-n-snap',
    storageBucket: 'snack-n-snap.appspot.com',
    iosBundleId: 'com.example.snackNApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk7Gkrd-aMyARTajK3765pSQHSmbXp32E',
    appId: '1:112575088036:ios:b275cb2010af1b66346d31',
    messagingSenderId: '112575088036',
    projectId: 'snack-n-snap',
    storageBucket: 'snack-n-snap.appspot.com',
    iosBundleId: 'com.example.snackNApp.RunnerTests',
  );
}
